"""message

Revision ID: 34a49c9dc607
Revises: 
Create Date: 2023-10-18 03:41:14.961374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a49c9dc607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_name', sa.String(), nullable=True),
    sa.Column('matchup', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('build_order', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_builds_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usergroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_usergroups_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usergroups_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opp_division', sa.String(), nullable=True),
    sa.Column('win_loss', sa.String(), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_results_build_id_builds')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usernotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_usernotes_build_id_builds')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usernotes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usernotes')
    op.drop_table('results')
    op.drop_table('usergroups')
    op.drop_table('builds')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
